version: "3"
services:
    backend:
        image: node:alpine
        working_dir: /app
        volumes:
            - ./apps/backend:/app
        command: npm run start
        restart: always
    frontend:
        image: node:alpine
        working_dir: /app
        volumes:
            - ./apps/frontend:/app
        command: npm run build
    nginx:
        image: nginx
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
            - target: 443
              published: 443
              protocol: tcp
              mode: host
        links:
            - backend
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./apps/frontend/dist:/usr/share/nginx/html
        restart: always
