version: '3'
services:
  app:
    image: node:alpine
    working_dir: /app
    volumes:
      - .:/app
    command: npm run dep
    restart: always
  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    links:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
  first_request:
    image: alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "apk --no-cache add curl && ./first-request.sh"
