version: '3.9'
services:
  app:
    image: node:alpine
    working_dir: /app
    volumes:
      - .:/app
    restart: always
    command: npm run dev
  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    links:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
